FROM docker.io/httpd:latest

RUN apt update && \
    apt install vim curl netcat-traditional -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
    
COPY configs/httpd.conf /usr/local/apache2/conf/httpd.conf

WORKDIR "/var/www"